site_name: Project Documentation
site_url: https://<username>.github.io/<repo>/
repo_url: https://github.com/<username>/<repo>
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - navigation.tabs
plugins:
  - search
  - mermaid2    
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.progressbar

extra_css:
  - styles/extra.css  # optional, for custom branding
nav:
  - Home: README.md
  - Getting Started: docs/getting-started.md
  - Architecture: docs/architecture.md
  - API Reference: docs/api-reference.md
  - Configuration: docs/configuration.md
  - Performance: docs/performance.md
  - Deployment: docs/deployment.md
  - Troubleshooting: docs/troubleshooting.md
